# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded Bdcom_autotest_bdproject 1.0 [list source [file join $dir Bdcom_autotest_bdproject.pkg.tcl]]
package ifneeded Bdcom_autotest_bdproject_ext 1.0 [list source [file join $dir Bdcom_autotest_bdproject_ext.pkg.tcl]]
package ifneeded Bdcom_autotest_expect 1.0 [list source [file join $dir Bdcom_autotest_expect.pkg.tcl]]
package ifneeded Bdcom_autotest_tester 1.0 [list source [file join $dir Bdcom_autotest_tester.pkg.tcl]]
package ifneeded Bdcom_autotest_topo 1.0 [list source [file join $dir Bdcom_autotest_topo.pkg.tcl]]
